AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: disable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false
